# OpenTofu compatibility test fixture
# Tests that Lambdaform correctly parses .tf files generated by/for OpenTofu
# OpenTofu uses identical HCL syntax but has its own registry and provider blocks

terraform {
  required_version = ">= 1.6.0" # OpenTofu versioning

  required_providers {
    aws = {
      source  = "registry.opentofu.org/hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "registry.opentofu.org/hashicorp/random"
      version = "~> 3.0"
    }
  }

  # OpenTofu supports state encryption (unique feature)
  encryption {
    key_provider "pbkdf2" "my_key" {
      passphrase = "test-passphrase"
    }
    method "aes_gcm" "my_method" {
      keys = key_provider.pbkdf2.my_key
    }
    state {
      method   = method.aes_gcm.my_method
      enforced = false
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

# Variable with OpenTofu-style validation
variable "environment" {
  type    = string
  default = "dev"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Must be dev, staging, or prod."
  }
}

# Locals using OpenTofu-compatible expressions
locals {
  prefix     = "opentofu-test"
  table_name = "${local.prefix}-users"
}

# Lambda with all standard attributes
resource "aws_lambda_function" "api" {
  function_name = "${local.prefix}-api"
  handler       = "index.handler"
  runtime       = "nodejs20.x"
  timeout       = 30
  memory_size   = 256
  filename      = "api.zip"

  environment {
    variables = {
      ENVIRONMENT = "dev"
      TABLE_NAME  = "users-table"
    }
  }

  layers = [
    aws_lambda_layer_version.shared.arn
  ]
}

# Python Lambda
resource "aws_lambda_function" "processor" {
  function_name = "${local.prefix}-processor"
  handler       = "main.handler"
  runtime       = "python3.12"
  timeout       = 60
  memory_size   = 512
  filename      = "processor.zip"

  environment {
    variables = {
      QUEUE_URL = "https://sqs.us-west-2.amazonaws.com/123456789/my-queue"
    }
  }
}

# Go Lambda (provided.al2023 custom runtime)
resource "aws_lambda_function" "worker" {
  function_name = "${local.prefix}-worker"
  handler       = "bootstrap"
  runtime       = "provided.al2023"
  timeout       = 120
  memory_size   = 128
  filename      = "worker.zip"

  environment {
    variables = {
      LOG_LEVEL = "info"
    }
  }
}

# Lambda layer
resource "aws_lambda_layer_version" "shared" {
  layer_name          = "${local.prefix}-shared"
  filename            = "layers/shared"
  compatible_runtimes = ["nodejs20.x", "python3.12"]
}

# REST API (v1)
resource "aws_api_gateway_rest_api" "main" {
  name        = "${local.prefix}-api"
  description = "OpenTofu-managed REST API"
}

resource "aws_api_gateway_resource" "users" {
  rest_api_id = aws_api_gateway_rest_api.main.id
  parent_id   = aws_api_gateway_rest_api.main.root_resource_id
  path_part   = "users"
}

resource "aws_api_gateway_method" "get_users" {
  rest_api_id   = aws_api_gateway_rest_api.main.id
  resource_id   = aws_api_gateway_resource.users.id
  http_method   = "GET"
  authorization = "NONE"
}

resource "aws_api_gateway_integration" "get_users" {
  rest_api_id             = aws_api_gateway_rest_api.main.id
  resource_id             = aws_api_gateway_resource.users.id
  http_method             = aws_api_gateway_method.get_users.http_method
  type                    = "AWS_PROXY"
  integration_http_method = "POST"
  uri                     = aws_lambda_function.api.invoke_arn
}

# HTTP API (v2)
resource "aws_apigatewayv2_api" "http" {
  name          = "${local.prefix}-http-api"
  protocol_type = "HTTP"
}

resource "aws_apigatewayv2_integration" "processor" {
  api_id             = aws_apigatewayv2_api.http.id
  integration_type   = "AWS_PROXY"
  integration_uri    = aws_lambda_function.processor.invoke_arn
}

resource "aws_apigatewayv2_route" "post_process" {
  api_id    = aws_apigatewayv2_api.http.id
  route_key = "POST /process"
  target    = aws_apigatewayv2_integration.processor.id
}

# DynamoDB table
resource "aws_dynamodb_table" "users" {
  name         = "users-table"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "pk"
  range_key    = "sk"

  attribute {
    name = "pk"
    type = "S"
  }

  attribute {
    name = "sk"
    type = "S"
  }

  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"
}

# SQS Queue
resource "aws_sqs_queue" "tasks" {
  name                       = "${local.prefix}-tasks"
  visibility_timeout_seconds = 60
}

# Event source mapping (SQS → Lambda)
resource "aws_lambda_event_source_mapping" "sqs_processor" {
  event_source_arn = aws_sqs_queue.tasks.arn
  function_name    = aws_lambda_function.processor.arn
  batch_size       = 5
  enabled          = true
}
